import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Service","description":"","frontmatter":{"editSource":"docs/cordis-api/service.zh.md","rawMarkdownPath":"reference/cordis-api/service.md"},"headers":[],"relativePath":"reference/cordis-api/service.md","filePath":"reference/cordis-api/service.md"}');
const _sfc_main = { name: "reference/cordis-api/service.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="service" tabindex="-1">Service <a class="header-anchor" href="#service" aria-label="Permalink to &quot;Service&quot;">​</a></h1><p>上下文服务的基类。以插件形式加载的子类会将自身注册为 <code>ctx.&lt;name&gt;</code>。</p><p>用于在 <code>ctx</code> 上公开具名 API 的服务基类。</p><p>子类在构造函数中调用 <code>super(ctx, name)</code>。服务会立即注册，并随所属 fiber 自动移除。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L11" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-name" tabindex="-1">service.name <a class="header-anchor" href="#service-name" aria-label="Permalink to &quot;service.name&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** The service name this instance is registered under. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">public name</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: string</span></span></code></pre></div><p>此实例注册时使用的服务名称。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L30" target="_blank" rel="noreferrer">源码</a></p><h2 id="静态成员" tabindex="-1">静态成员 <a class="header-anchor" href="#静态成员" aria-label="Permalink to &quot;静态成员&quot;">​</a></h2><h3 id="service-init" tabindex="-1">Service.init <a class="header-anchor" href="#service-init" aria-label="Permalink to &quot;Service.init&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of an instance method run after construction (class plugins). */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">init</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>构造完成后运行的实例方法所使用的符号键（类插件）。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L13" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-check" tabindex="-1">Service.check <a class="header-anchor" href="#service-check" aria-label="Permalink to &quot;Service.check&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the availability predicate passed to \`ctx.provide()\`. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">check</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>传给 <code>ctx.provide()</code> 的可用性谓词所使用的符号键。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L15" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-config" tabindex="-1">Service.config <a class="header-anchor" href="#service-config" aria-label="Permalink to &quot;Service.config&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the phantom intercept-config type parameter. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">config</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>虚设拦截配置类型参数所使用的符号键。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L17" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-invoke" tabindex="-1">Service.invoke <a class="header-anchor" href="#service-invoke" aria-label="Permalink to &quot;Service.invoke&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the call body making a service callable (e.g. \`ctx.logger()\`). */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">invoke</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>使服务可被调用的调用体所使用的符号键（例如 <code>ctx.logger()</code>）。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L19" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-extend" tabindex="-1">Service.extend <a class="header-anchor" href="#service-extend" aria-label="Permalink to &quot;Service.extend&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the helper deriving an extended service instance. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">extend</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>用于派生扩展服务实例的辅助方法所使用的符号键。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L21" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-tracker" tabindex="-1">Service.tracker <a class="header-anchor" href="#service-tracker" aria-label="Permalink to &quot;Service.tracker&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the tracker metadata used for context tracing. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">tracker</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>上下文追踪所用跟踪器元数据的符号键。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L23" target="_blank" rel="noreferrer">源码</a></p><h3 id="service-resolveconfig" tabindex="-1">Service.resolveConfig <a class="header-anchor" href="#service-resolveconfig" aria-label="Permalink to &quot;Service.resolveConfig&quot;">​</a></h3><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">/** Symbol key of the intercept-config resolution helper below. */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">static readonly </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">resolveConfig</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: unique symbol</span></span></code></pre></div><p>下述拦截配置解析辅助方法所使用的符号键。</p><p><a href="https://github.com/deepseek-ai/deepseek-harness/blob/master/vendor/cordis/src/service.ts#L25" target="_blank" rel="noreferrer">源码</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("reference/cordis-api/service.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const service = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  service as default
};
